### ISSUE TITLE
 where can i download ThoughtsWeaver AKA WebWeaver C++ wiki clone ? 

### ISSUE THREAD

**Issue by topstarnetwork** [WardCunningham/remodeling#16]
Hello, could you please tell me where I candownload ThoughtsWeaver AKA WebWeaver C++ wiki clone ? Regards, Heather

**Comment by WardCunningham** [comment]
Perhaps @jcoplien can help?

**Comment by jcoplien** [comment]
I have the source and would be glad to send it to you. It looks like the last time I used it was about 11 years ago, and parts of it are 20 years old. But I write code quite simply and to be portable so I doubt that C++ evolution will much get in your way. And some of it is Shell, which is probably backwards compatible to the dark ages.

I'm curious why you want to use it instead of one of the more modern Wikis. It *did* have some nice features without all the baggage that modern Wiki-like environments have brought. It used Ward's original markup, with maybe some minor differences that I have a hard time recalling, but I think Ward's wiki had a bug in nested lists, or something, which ThoughtsWeaver fixed. It had page-level notification and a portable security system which, though not airtight, was "good enough" and very unobtrusive to use. The "database" is simple, portable, and implemented with simple files that are human-readable in a pinch. There was also an explicit syntax for references across Wiki instances.

The real gem was the weaver program that went with it. We authored an entire book in ThoughtsWeaver (the Organisational Patterns book) and used the tool to generated Frame files which we sent directly to the publisher. The publisher just substituted their own style sheet, and we had a book. We're doing the same thing now with Google Sites (yuk) for the generation of the Scrum Patterns book. You can see an archive of the pages generated by ThoughtsWeaver at: http://orgpatterns.wikispaces.com. The book was generated from them. I probably also have the weaver program stashed away somewhere.

Write me here on GitHub if you'd like a tar file, and let me know where to send it.

**Comment by WardCunningham** [comment]
Thanks for the update.

**Comment by topstarnetwork** [comment]
This is very kind of you,
you can send your zip file to:
heather@trans-world.org
or
heather.raffaella@gmail.com

The reason I was intrested in this c++ wiki engine is because I think c++ is less cpu consuming,
I know there are so great perl and java wiki engines outhere wich I will use for other perl or java projects also but as far as my c++ groupware is concered it would be nice to build it with a c++wiki wich I think yours is very nice to use as well.
As you are a great epert in c++ would you be abel to recomend me also some kind of c++ cm+ groupwware? I know there is a cpp cms and a c++ open source seerver engine but these need to be built from scratch,
regards, Heather

**Comment by topstarnetwork** [comment]
Would you mind also sending  the weaver program  with the c++ wiki clone as attatchment as well?
Regards, Heather

**Comment by jcoplien** [comment]
I’ll try to hunt it down. No luck so far.
