### ISSUE TITLE
Pages that have been moved

### ISSUE THREAD

**Issue by paul90** [WardCunningham/remodeling#26]
I notice that pages that have moved(?) just display
```
Trouble Encountered
Page unavailable until conversion completed.
See github
```
with a link to #2. For example http://wiki.c2.com/?DefinitionOfHomoiconic , which appears to have moved to http://wiki.c2.com/?DefinitionOfHomoiconicDiscussion

**Comment by WardCunningham** [comment]
I know I have pages with encoding problems because my converter script threw errors that I logged.

In the case you mention I think there are two pages only one of which is missing. There was a sometimes used convention of making secondary pages for discussion. These were inspired by Wikipedia's talk pages.

I do really need to recover the missing pages. Thanks for the reminder. Perhaps I can split pages into fragments, experimentally discover what divergent encoding is present in each fragment, convert them, then reassemble the page into a single consistently encoded file.
