### ISSUE TITLE
Alternate approaches for "page transitions without reloading javascript"

### ISSUE THREAD

**Issue by nateberkopec** [WardCunningham/remodeling#7]
It looks like you're already set to go down the path of "single page application with JSON data", but I wanted to bring up two approaches you may not be aware of:
- [`pjax`](https://github.com/defunkt/jquery-pjax) - jQuery + pushState to swap HTML content inside of a container.
- [`Turbolinks`](https://github.com/turbolinks/turbolinks) Designed for Rails but compatible with any website. JQuery not required. Progressive enhancement. Side effect: would be able browse the Wiki with Javascript turned off.

Feel free to close, just a suggestion from the peanut gallery. You may have other reasons for wanting the site data in a JSON, rather than HTML format.

**Comment by WardCunningham** [comment]
Thanks for the two pointers.

My first attempt at translation fetched my native db file format but this had huge character set problems and couldn't even be read by javascript. JSON was my next choice because my native format was already key-value pairs.

You do raise a good question, how far down the SPA road do we want to go? Or, how far down the road can we go and still describe the viewing experience as "historically accurate"?

I would love to have the side-by-side viewing experience of federated wiki which is an easy add now that the client is in control. I would love to see more discussion of these "phase #2" decisions here in the issues.

**Comment by WardCunningham** [comment]
Experience shows that browser caching and the overlap provided by 1708d77d and 28f1a05b provide acceptable performance. Our concern here has been premature.

![image](https://cloud.githubusercontent.com/assets/12127/20032858/a1ed2b14-a350-11e6-8c8b-d8c23861caa1.png)
